### ISSUE TITLE
Any possibility on making this free and open source?

### ISSUE THREAD

**Issue by abetusk** [ekg/fastahack#8]
I see that libdisorder is under GPL(v2) but that the rest of the source is not under a free license.  Is there any possibility that fastahack could be put under a free license?

**Comment by rekado** [comment]
I'm interested in this, too, as I'd like it to be packaged for GNU Guix.  Fasta.cpp and Fasta.h contain "All rights reserved" notices.  Is there any way to release them under a free license?

**Comment by ekg** [comment]
They should be under an open license. Let me make that change.

**Comment by roelj** [comment]
Any progress on this?

**Comment by robsyme** [comment]
I'd also be very appreciative if the licencing was made clear for fastahack (as well as smithwaterman, intervaltree, multichoose, and tabixpp). 

P.S. Congratulations on the PBWT manuscript

**Comment by tillea** [comment]
Same here as for libsmithwaterman:  To package for Debian a free license is needed.  I'd like to package freebayes for Debian and all its predependencies need a free license.

**Comment by ekg** [comment]
They should all be under a free license... Is there anything we can't
simply add an MIT license to?

**Comment by tillea** [comment]
Hi Erik,

thanks for your quick response.  Could you please at least drop a
LICENSE file into the git repository that specifies this?  Otherwise per
definition a code with no explicite license is non-free.

Kind regards

      Andreas.

On Fri, Jul 01, 2016 at 12:35:10AM -0700, Erik Garrison wrote:
> They should all be under a free license... Is there anything we can't
> simply add an MIT license to?
> 
> On Fri, Jul 1, 2016, 09:27 Andreas Tille <notifications@github.com> wrote:
> 
> > Same here as for libsmithwaterman: To package for Debian a free license is
> > needed. I'd like to package freebayes for Debian and all its
> > predependencies need a free license.
> >
> > —
> > You are receiving this because you commented.
> >
> > Reply to this email directly, view it on GitHub
> > <https://github.com/ekg/fastahack/issues/8#issuecomment-229875874>, or mute
> > the thread
> > <https://github.com/notifications/unsubscribe/AAI4ERfgt3wQo7CbohXBeM8KZirc69qhks5qRMFMgaJpZM4GbXRl>
> > .
> >
> 
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ekg/fastahack/issues/8#issuecomment-229877634

-- 
http://fam-tille.de

**Comment by ekg** [comment]
Yes, I will do so.

For packaging, we are in the process of setting as default commonly used
options. It would be good if the packaged version were made after these
changes.

**Comment by tillea** [comment]
Hi Erik,

On Fri, Jul 01, 2016 at 01:01:30AM -0700, Erik Garrison wrote:
> Yes, I will do so.

Thanks a lot.
 
> For packaging, we are in the process of setting as default commonly used
> options. It would be good if the packaged version were made after these
> changes.

Thanks for this helpful information.  However, I think I'll go with the
current version for a start since for new software it takes some time to
"pass the entrance" into Debian.  Once some software is in we can apply
changes quite quickly.

If you speak about new structure:  For Debian I have separately packaged
libdisorder to avoid a code duplication.  You can download the package
source from

   https://packages.debian.org/source/unstable/libdisorder

or from packaging git that is linked from there.

May be this helps.

Kind regards

      Andreas.

-- 
http://fam-tille.de

**Comment by ekg** [comment]
Right, that makes sense. Getting it in first is a harder step than updating
the default parameters and bumping the version. Thank you so much for doing
this. Debian is awesome and it will be amazing to have freebayes and
related tools available there. I will apply the licenses within the next
few hours (need to get back to a connected computer).

**Comment by roelj** [comment]
Any luck yet?

**Comment by rekado** [comment]
@ekg Thank you for adding the LICENSE file!

It would be very nice if you could also update the file headers to mention the license, because right now Fasta.cpp still says "All rights reserved", which makes it impossible for us to assume that the LICENSE file also applies to Fasta.cpp.

I'm looking forward to seeing this packaged for GNU Guix and other GNU/Linux distributions!

**Comment by rekado** [comment]
This is a friendly ping :)

We'd still like to be able to package it for GNU Guix.

**Comment by ekg** [comment]
All the file headers need to have the license?

**Comment by abetusk** [comment]
FWIW here's what the FSF says about it:

* [Is it enough just to put a copy of the GNU GPL in my repository?](https://www.gnu.org/licenses/gpl-faq.html#LicenseCopyOnly)
* [Why should I put a license notice in each source file?](https://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile)

**Comment by tillea** [comment]
Since the LICENSE file is there the needed conditions are fullfilled.  Package is accepted by Debian ftpmaster so the license was also verified.  I think the issue can be closed.

**Comment by tillea** [comment]
I can confirm that Debian ftpmasters have accepted the package inside Debian which is a good sign that there are people who are quite picky about licenses agree that this bug can be closed.  Doing a real release (see issue 14) would be nice.
